const ClientStage = require("../model/clientStageSchema");

// =================================================
// HELPERS
// =================================================

const escapeRegex = (value) => {
  return String(value || "").replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
};

// =================================================
// CREATE SAFE STAGE KEY
// =================================================

const createBaseStageKey = (name) => {
  const normalized = String(name || "")
    .normalize("NFKD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-zA-Z0-9]+/g, " ")
    .trim();

  if (!normalized) {
    return "customStage";
  }

  const words = normalized.split(/\s+/);

  let key = words
    .map((word, index) => {
      const lower = word.toLowerCase();

      if (index === 0) {
        return lower;
      }

      return lower.charAt(0).toUpperCase() + lower.slice(1);
    })
    .join("");

  if (/^\d/.test(key)) {
    key = `stage${key}`;
  }

  return key || "customStage";
};

// =================================================
// UNIQUE KEY
// =================================================

const generateUniqueStageKey = async (name) => {
  const baseKey = createBaseStageKey(name);

  let key = baseKey;
  let suffix = 2;

  while (
    await ClientStage.exists({
      key,
    })
  ) {
    key = `${baseKey}${suffix}`;
    suffix += 1;
  }

  return key;
};

// =================================================
// GET STAGES
//
// GET /api/stages
// =================================================

exports.getStages = async (req, res) => {
  try {
    const stages = await ClientStage.find({})
      .sort({
        displayOrder: 1,
        createdAt: 1,
      })
      .lean();

    return res.status(200).json({
      success: true,
      count: stages.length,
      data: stages,
    });
  } catch (error) {
    console.error("GET STAGES ERROR:", error);

    return res.status(500).json({
      success: false,
      message: error.message || "Failed to load stages.",
    });
  }
};

// =================================================
// CREATE STAGE
//
// POST /api/stages
//
// {
//   "name": "Interview Preparation",
//   "amount": 50000
// }
//
// IMPORTANT:
// - key generated by backend
// - displayOrder generated by backend
// - only superadmin route should call this
// =================================================

exports.createStage = async (req, res) => {
  try {
    const name = String(req.body.name || "").trim();

    const amount = Number(req.body.amount);

    // =================================================
    // VALIDATION
    // =================================================

    if (!name) {
      return res.status(400).json({
        success: false,
        message: "Stage name is required.",
      });
    }

    if (name.length > 150) {
      return res.status(400).json({
        success: false,
        message: "Stage name cannot exceed 150 characters.",
      });
    }

    if (!Number.isFinite(amount)) {
      return res.status(400).json({
        success: false,
        message: "Stage amount must be a valid number.",
      });
    }

    if (amount < 0) {
      return res.status(400).json({
        success: false,
        message: "Stage amount cannot be negative.",
      });
    }

    if (!Number.isInteger(amount)) {
      return res.status(400).json({
        success: false,
        message: "Stage amount must be a whole number of yen.",
      });
    }

    // =================================================
    // DUPLICATE NAME
    // =================================================

    const duplicate = await ClientStage.findOne({
      name: {
        $regex: `^${escapeRegex(name)}$`,
        $options: "i",
      },
    }).lean();

    if (duplicate) {
      return res.status(409).json({
        success: false,
        message: "A stage with this name already exists.",
      });
    }

    // =================================================
    // KEY
    // =================================================

    const key = await generateUniqueStageKey(name);

    // =================================================
    // DISPLAY ORDER
    // =================================================

    const lastStage = await ClientStage.findOne({})
      .sort({
        displayOrder: -1,
      })
      .select("displayOrder")
      .lean();

    const displayOrder = Number(lastStage?.displayOrder || 0) + 1;

    // =================================================
    // AUDIT
    // =================================================

    const userId = String(req.user.id || req.user.staffId || "");

    const userName = String(req.user.name || "Unknown");

    // =================================================
    // CREATE
    // =================================================

    const stage = await ClientStage.create({
      key,

      name,

      amount,

      isActive: true,

      isSystem: false,

      displayOrder,

      createdById: userId,

      createdByName: userName,

      updatedById: userId,

      updatedByName: userName,
    });

    return res.status(201).json({
      success: true,

      message: "Client stage created successfully.",

      data: stage.toObject(),
    });
  } catch (error) {
    console.error("CREATE STAGE ERROR:", error);

    if (error.code === 11000) {
      return res.status(409).json({
        success: false,
        message: "A stage with the same key already exists.",
      });
    }

    if (error.name === "ValidationError") {
      return res.status(400).json({
        success: false,
        message: error.message,
      });
    }

    return res.status(500).json({
      success: false,
      message: error.message || "Failed to create stage.",
    });
  }
};
